apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingressClassName: nginx
  name: altruist-ingress
  namespace: altruist
spec:
  rules:
    - host: altruist.tst.com
      http:
        paths:          
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: altruist-service
              port: 
                number: 8085
  tls:
    - hosts:
        - altruist.tst.com


#nginx namespace is out of altruist namespace