services:
  prometheus:
    image: prom/prometheus
    container_name: altruist-prometheus
    volumes:
      - ./src/app/prometheus_metrics/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - metrics-promaggregationgateway
    networks:
      - altruist-network
    profiles: [dependency_only]

  metrics-promaggregationgateway:
    image: ghcr.io/zapier/prom-aggregation-gateway:v0.9.0
    container_name: altruist-prom-aggregation-gateway
    ports:
      - 9091:80
    command:
      - "--apiListen=:80"
    networks:
      - altruist-network
    profiles: [dependency_only]

  altruist-backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: altruist-backend
    image: altruist-backend:v${GIT_COMMIT:-notSetted}
    restart: on-failure
    ports:
      - 8085:8085
    environment:
      PROMETHEUS_PROMAGGREGATIONGATEWAY_URL: "http://altruist-prom-aggregation-gateway"
      REDIS_HOST: "altruist-redis"
    networks:
      - altruist-network
    profiles: [backend]

  dozzle:
    container_name: altruist-dozzle
    image: ghcr.io/amir20/dozzle:v8.12.3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8089:8080
    profiles: [dependency_only]

  altruist-redis:
    image: redis:7
    container_name: altruist-redis
    ports:
      - 6379:6379
    networks:
      - altruist-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
    profiles: [dependency_only]

networks:
  altruist-network:
    driver: bridge
    name: altruist-network
