apiVersion: v1
kind: Service
metadata:
  name: __TEMPLATE_PROJECT_NAME__-dozzle
  namespace: __TEMPLATE_PROJECT_NAME__
spec:
  ports:
    - name: "8089"
      port: 8089
      targetPort: 8089
      protocol: TCP
  type: ClusterIP
  selector:
    app: __TEMPLATE_PROJECT_NAME__-dozzle

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: __TEMPLATE_PROJECT_NAME__-dozzle
  namespace: __TEMPLATE_PROJECT_NAME__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: __TEMPLATE_PROJECT_NAME__-dozzle
  template:
    metadata:
      labels:
        app: __TEMPLATE_PROJECT_NAME__-dozzle
    spec:   
      serviceAccountName: __TEMPLATE_PROJECT_NAME__-pod-viewer
      containers:
      - name: __TEMPLATE_PROJECT_NAME__-dozzle
        image: ghcr.io/amir20/dozzle:v8.12.3         
        ports:
          - containerPort: 8089
            protocol: TCP
        env:
            - name: DOZZLE_MODE
              value: "k8s"
            #unccomment the following line to set a namespace
            #- name: DOZZLE_NAMESPACE
            #  value: "__TEMPLATE_PROJECT_NAME__"
            - name: DOZZLE_ADDR
              value: ":8089"
      restartPolicy: Always

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: __TEMPLATE_PROJECT_NAME__-pod-viewer
  namespace: __TEMPLATE_PROJECT_NAME__

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: __TEMPLATE_PROJECT_NAME__-pod-viewer-binding
  namespace: __TEMPLATE_PROJECT_NAME__
subjects:
  - kind: ServiceAccount
    name: __TEMPLATE_PROJECT_NAME__-pod-viewer
    namespace: __TEMPLATE_PROJECT_NAME__
roleRef:
  kind: ClusterRole
  name: __TEMPLATE_PROJECT_NAME__-pod-viewer-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: __TEMPLATE_PROJECT_NAME__-pod-viewer-role
  namespace: __TEMPLATE_PROJECT_NAME__
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods"]
    verbs: ["get", "list"]