apiVersion: v1
kind: Service
metadata:
  name: altruist-prom-aggregation-gateway
  namespace: altruist
spec:
  ports:
    - name: "9091"
      port: 9091
      targetPort: 80
  type: ClusterIP
  selector:
    app: altruist-prom-aggregation-gateway
  



---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: altruist-prom-aggregation-gateway
  namespace: altruist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: altruist-prom-aggregation-gateway
  template:
    metadata:
      labels:
        app: altruist-prom-aggregation-gateway
    spec:   
      containers:
      - name: altruist-prom-aggregation-gateway
        image: ghcr.io/zapier/prom-aggregation-gateway:v0.9.0        
        args:
        - --apiListen=:80        
        ports:
          - containerPort: 80
            protocol: TCP
      restartPolicy: Always




