apiVersion: v1
kind: Service
metadata:
  name: __TEMPLATE_PROJECT_NAME__-prometheus
  namespace: __TEMPLATE_PROJECT_NAME__
spec:
  ports:
   - name: "9090"
     port: 9090
     targetPort: 9090
  type: ClusterIP
  selector:
    app: __TEMPLATE_PROJECT_NAME__-prometheus

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: __TEMPLATE_PROJECT_NAME__-prometheus
  namespace: __TEMPLATE_PROJECT_NAME__
spec:
  replicas: 1
  selector:
    matchLabels:
      app: __TEMPLATE_PROJECT_NAME__-prometheus
  template:
    metadata:
      labels:
        app: __TEMPLATE_PROJECT_NAME__-prometheus
    spec:   
      containers:
      - image: prom/prometheus #missing version
        name: __TEMPLATE_PROJECT_NAME__-prometheus
        ports:
          - containerPort: 9090
            protocol: TCP
        volumeMounts:
          - mountPath: /etc/prometheus/prometheus.yml
            name: prometheus-cm0
            readOnly: true
            subPath: prometheus.yml
      restartPolicy: Always
      volumes:
      - configMap:
          items:
            - key: prometheus.yml
              path: prometheus.yml
          name: prometheus-cm0
        name: prometheus-cm0
