apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cm0
  namespace: __TEMPLATE_PROJECT_NAME__
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'aggregation_gateway'
        static_configs:
          - targets: ['__TEMPLATE_PROJECT_NAME__-prom-aggregation-gateway:80']
        honor_labels: true





