apiVersion: v1
kind: Service
metadata:
  name: altruist-redis
  namespace: altruist
spec:
  ports:
    - port: 6379
  selector:
    app: altruist-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: altruist-redis
  namespace: altruist
spec:
  selector:
    matchLabels:
      app: altruist-redis
  template:
    metadata:
      labels:
        app: altruist-redis
    spec:
      containers:
        - name: altruist-redis
          image: redis:7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
