apiVersion: v1
kind: Service
metadata:
  name: __TEMPLATE_PROJECT_NAME__-redis
  namespace: __TEMPLATE_PROJECT_NAME__
spec:
  ports:
    - port: 6379
  selector:
    app: __TEMPLATE_PROJECT_NAME__-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: __TEMPLATE_PROJECT_NAME__-redis
  namespace: __TEMPLATE_PROJECT_NAME__
spec:
  selector:
    matchLabels:
      app: __TEMPLATE_PROJECT_NAME__-redis
  template:
    metadata:
      labels:
        app: __TEMPLATE_PROJECT_NAME__-redis
    spec:
      containers:
        - name: __TEMPLATE_PROJECT_NAME__-redis
          image: redis:7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
