apiVersion: v1
kind: Service
metadata:
  name: __TEMPLATE_PROJECT_NAME__-service
  namespace: __TEMPLATE_PROJECT_NAME__
spec:
  ports:
  - port: 8085
    name: http
  type: LoadBalancer
  selector:
    app: __TEMPLATE_PROJECT_NAME__-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: __TEMPLATE_PROJECT_NAME__-service
  namespace: __TEMPLATE_PROJECT_NAME__
spec:
  selector:
    matchLabels:
      app: __TEMPLATE_PROJECT_NAME__-service
  template:
    metadata:
      labels:
        app: __TEMPLATE_PROJECT_NAME__-service
    spec:
      containers:
      - name: __TEMPLATE_PROJECT_NAME__-service
        image: __TEMPLATE_PROJECT_NAME__-service
        ports:
        - containerPort: 8085
        env:
        - name: PROMETHEUS_PROMAGGREGATIONGATEWAY_URL
          value: "__TEMPLATE_PROJECT_NAME__-prom-aggregation-gateway:9091"
        - name: REDIS_HOST
          value: "__TEMPLATE_PROJECT_NAME__-redis"
        - name: REDIS_PORT
          value: "6379"

#### deploy on the same network
